# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
units: bin/units.tsv
# path or URL to contrast sheet (TSV format, columns: sample, condition, ...)
contrasts: bin/contrasts.tsv

ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/sequence/mm10_gencode.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/sequence/mm10_gencode.fa.fai
  # path/to/STAR/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/indexes/star
  salmon_index:   /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/indexes/salmon/mm10_gencode
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/annotation/mm10_gencode.gtf
  # known variants (Broad resource downloaded here: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/mm10/v0/)
  known_snps:
  known_indels:
  snpeff_db_id:
# are the sequencing reads paired-end ('PE') or single-end ('SE')
PE_or_SE: PE

# what is the strandedness of the kit used for library prep?
# options: "forward", "reverse", "unstranded" (usually reverse)
strandedness: reverse

### EdgeR Variables ###

# used for annotation. see src/annotation.tsv for common_name options. e.g.:  "mouse", "human", "fly"
common_name: mouse
# differential expression cutoff values
logfc.filter: 1
fdr.filter: 0.05

# Boolean for whether to call variants. Requires 'variant_calling_units.tsv'
# snpRelate html report only generated if conda is callable. Otherwise, the snpRelate rule is not run.
call_variants: false
